server:
  port: 8080
  servlet:
    context-path: /springboot_study

spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/springboot_study'
    username: root
    password: rootroot
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "+/1MvzstOesOssUYIrGk9tw6cK8t3N+10u1um60M6XrtaEmG0+KBEqk+4z/Fz/k+"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds
